### ISSUE TITLE
Fluency loss

### ISSUE THREAD

**Issue by sunwoo76** [YuxinWenRick/hard-prompts-made-easy#17]
Does this version of the code reflect fluency loss?

Thanks :)

**Comment by YuxinWenRick** [comment]
Hi, we don't have fluency loss on the prompt inversion trained on the CLIP model, because we need another autoregressive language model which shares the same tokenizer and word embeddings with CLIP to calculate the loss, but to our knowledge, such a model is not available online. Therefore we have to train an autoregressive language model from scratch, which is very expensive for us.

However, we do include `fluency_weight` in our lm prompt tuning code. Because we use gpt-2 model, we can get fluency constraint for free.
