### ISSUE TITLE
Is the evaluation code for PEZ available?

### ISSUE THREAD

**Issue by SydCS** [YuxinWenRick/hard-prompts-made-easy#29]
The method is evaluated in randomly sampled 100 data points across 4 different datasets. Are that code and sample indices available? Thanks!

**Comment by YuxinWenRick** [comment]
Hi @SydCS, thanks for asking. Our code is a little hard to clean rn since we load our local dataset on our cluster. However, the eval code is very easy to set up, you can first load the Hugging Face dataset (maybe with streaming) to get the image, and then, generate the prompt with PEZ with this function: [optimize_prompt](https://github.com/YuxinWenRick/hard-prompts-made-easy/blob/main/optim_utils.py#L222). After you get the prompt, you get the generated images with stable diffusion, and at the end you get the CLIP scores between the original image and the generated image.

In high-level, the code looks like:
```
# load dataset
dataset = load_dataset("detection-datasets/coco", split="val", streaming=True)
dataset_iter = iter(dataset)

# get all images
images = []
for _ in range(100):
    images.append(next(dataset)["image"])

for img in images:
    # get prompt
    prompt = optimize_prompt(..., target_images=[img])

    # generate image with SD
    gen_img = pipe(prompt).images

    # use (Open)CLIP to evaluate
    ori_feat = clip_model.encode_image(img)
    gen_feat = clip_model.encode_image(gen_img)
    ori_feat = ori_feat / ori_feat.norm(dim=1, keepdim=True)
    gen_feat = gen_feat / gen_feat.norm(dim=1, keepdim=True)
    clip_score = (ori_feat @ gen_feat.t()).mean().item()
```

Please let me know if you have any further questions.

**Comment by SydCS** [comment]
Thanks a lot for this detailed answer!
